config/routes.rb
Funnies::Application.routes.draw do

  match '/about' => 'pages#about', as: :about
  match '/copyright' => 'pages#copyright', as: :copyright

  scope "/blog" do
    resources :posts
    root to: "posts#index"
  end

  devise_for :users
  devise_scope :users do
    resources :suggestions, except: [:destroy]
    resources :subscriptions, only: [:index, :create, :destroy]
    resources :comics
    get "comics", to: "comics#index", as: :user_root
  end

  scope "/:username", as: "user" do
    resources :comics
    root to: "comics#index"
  end

  resources :comics do
    resource :subscriptions, only: [:index, :create, :destroy]
  end

  root to: "pages#landing"
end

app/models/comic.rb
require 'open-uri'

class Comic < ActiveRecord::Base
  has_many :subscriptions, dependent: :destroy
  has_many :readers, through: :subscriptions, source: :user
  has_many :comic_strips, dependent: :destroy

  validates_presence_of :name, :homepage, :comic_page
  validates :xpath_title, presence: true, xpath: true
  validates :xpath_image, presence: true, xpath: true

  attr_accessible :name, :homepage, :comic_page, :xpath_title, :xpath_image

  def update_strip
    if source_image_url.present?
      hash = Digest::MD5.hexdigest(open(source_image_url).read)
      unless ComicStrip.find_by_md5_hash(hash) # if didn't have, create it!
        comic_strips.create(:remote_comic_image_url => source_image_url)
      end
    end
  end
  
  private # I add it

  def source_image_url
    # get the page, after get the image url. if is abs path return it, else add homepage to it
    begin
      doc = Nokogiri::HTML(open(self.comic_page))
      image_url = doc.xpath("#{xpath_image}/@src").to_s
      return unless image_url.present?
      unless image_url.match(/^http:\/\//)
        image_url = "#{self.homepage}/#{image_url}"
      end
      image_url
    rescue Exception => e
      if !Rails.env.development? && defined?(HoptoadNotifier)
        HoptoadNotifier.notify(
          :error_class   => "Comic#source_image_url",
          :error_message => "Failed to parse image via XPath: #{e.message}",
          :parameters    => { "name" => name, "xpath_image" => xpath_image }
        )
      end
      logger.info "failed to parse image:", e
      nil
    end
  end
end

app/models/comic_strip.rb
class ComicStrip < ActiveRecord::Base
  belongs_to :comic

  validates_presence_of :comic, :comic_image

  attr_accessible :comic_id

  mount_uploader :comic_image, ComicImageUploader

  def md5_hash
    read_attribute(:md5_hash) || generate_md5!
  end
  
  private
  def generate_md5!
    save! if new_record?
    hash = Digest::MD5.hexdigest(File.read(comic_image.current_path))
    update_attribute(:md5_hash, hash)
    hash
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :body, :title, :user_id

  default_scope order: 'created_at DESC'

  attr_accessible :body, :title
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :comic
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :name, :website, :reason

  attr_accessible :name, :website, :reason

  state_machine initial: :open do
    event :accept do
      transition open: :accepted
    end

    event :reject do
      transition open: :rejected
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :subscriptions
  has_many :comics, :through => :subscriptions
  has_many :posts
  has_many :suggestions

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  attr_accessor :login
  attr_accessible :username, :email, :login,
                  :password, :password_confirmation, :remember_me

  validates :username, presence: true, uniqueness: true

  def subscribed?(comic)
    comics.include?(comic)
  end

  def subscribe!(comic)
    comics << comic unless subscribed?(comic)
  end

  def unsubscribe!(comic)
    subscriptions.find_by_comic_id(comic).destroy unless !subscribed?(comic)
  end

  def to_param
    username.parameterize
  end

  protected

  def self.find_for_database_authentication(conditions) # devise
    login = conditions.delete(:login)
    where(conditions).where(["username = :value OR email = :value",
                             { :value => login }]).first
  end
end

app/controllers/application_controller.rb
# encoding: utf-8
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder # Configuring your own responder

  protect_from_forgery

  layout :layout_by_resource

  def authenticated # login required
    redirect_to root_url unless user_signed_in?
  end

  def authenticate_admin # admin required
    unless current_user.admin?
      redirect_to :back, alert: "非法操作，您无权限进行此操作。"
    end
  end

  private

  def after_sign_in_path_for(resource_or_scope) # overwrite, which in devise
    case resource_or_scope
    when :user, User
      user_comics_path(:username => current_user.username)
    else
      super
    end
  end

  def layout_by_resource
    if devise_controller?
      "session"
    else
      "application"
    end
  end
end

app/controllers/comics_controller.rb
class ComicsController < InheritedResources::Base
  respond_to :rss, only: :index

  before_filter :authenticate_unless_rss
  before_filter :authenticate_admin, except: :index

  expose :comic
  expose(:comics) do
    User.find_by_username(params[:username]).try(:comics) || Comic.all
  end

  def create
    create! { collection_url }
  end

  def update
    update! { collection_url }
  end

  private
  def authenticate_unless_rss
    authenticated unless request.format.to_s[/rss/]
  end
  hide_action :authenticate_unless_rss
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def landing
  end

  def about
  end

  def copyright
  end
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  before_filter :authenticated, except: :index
  before_filter :authenticate_admin, except: :index

  expose :post
  expose(:posts) { Post.all }

  def create
    post.user = current_user
    if post.save
      redirect_to collection_url 
    else
      render :new
    end
  end

  def update
    update! { collection_url }
  end

end

app/controllers/subscriptions_controller.rb
# encoding: utf-8
class SubscriptionsController < ApplicationController

  expose(:comic) { Comic.find(params[:comic_id]) }

  def create
    current_user.subscribe!(comic)
    redirect_to comics_path, :notice => "订阅 #{comic.name} 成功！"
  end

  def destroy
    current_user.unsubscribe!(comic)
    redirect_to comics_path, :notice => "取消订阅 #{comic.name} 成功！"
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  expose :suggestion

  before_filter :authenticated

  def create
    suggestion.user = current_user
    suggestion.save
    respond_with(suggestion, location: comics_path)
  end
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper
  def admin_nav_link
    if controller_class == "posts"
      link_to "添加新博客", new_post_path
    else
      link_to "添加新漫画", new_comic_path
    end
  end
  
  private
  def controller_class
    controller.class.name.match(/(.+)Controller/)[1].downcase
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.username,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/comics/_comic.html.haml
- comics.each do |comic|
  %article.comic
    %header.title
      %h4= link_to comic.name, comic.homepage
    .comic_strip
      - if comic.comic_strips.any?
        = image_tag comic.comic_strips.last.comic_image_url
      - else
        %h5 不好意思，还没有漫画系列在此连载。
  %ul.comic_nav
    - if current_user.subscribed?(comic)
      %li= link_to "取消订阅", comic_subscriptions_path(comic), method: :delete, class: "button unsubscribe"
    - else
      %li= link_to "订阅", comic_subscriptions_path(comic), method: :post, class: "button subscribe"
    - if current_user.admin?
      %li= link_to "编辑此漫画", edit_comic_path(comic), class: "button admin_button"
      %li= link_to "删除此漫画", comic_path(comic), method: :delete, confirm: "您真的要删除此漫画吗？", class: "button admin_button"

app/views/comics/_form.html.haml
= semantic_form_for comic do |f|
  = f.semantic_errors
  = f.inputs do
    = f.input :name
    = f.input :homepage
    = f.input :comic_page
    = f.input :xpath_title
    = f.input :xpath_image
  = f.buttons do
    = f.commit_button label: "保存"

app/views/comics/edit.html.haml
= render 'form'

app/views/comics/index.html.haml
- unless params[:username]
  #suggestion
    %h3 列表里没有我想看的漫画？ #{link_to "建议添加", new_suggestion_path}

- if comics.any?
  = render :partial => 'comic'
- else
  - if params[:username]
    - if params[:username] == current_user.username
      %h1 您还没有订阅任何的漫画，#{link_to "点击进入", comics_path} 漫画列表订阅！
    - else
      %h1 您还没有订阅任何的漫画。
  - else
    %h1 不好意思，当前系统还没有任何漫画可阅读。

app/views/comics/new.html.haml
= render 'form'

app/views/layouts/application.html.haml
!!!
/[if IE 7 ] <html lang="en" class="no-js ie7">
/[if IE 8 ] <html lang="en" class="no-js ie8">
/[if IE 9 ] <html lang="en" class="no-js ie9">
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
%head
  %meta{charset: "utf-8"}
  %title 欢迎来到 funniesapp 漫画世界！
  = stylesheet_link_tag "funnies"
  = csrf_meta_tag
%body
  - if flash[:notice] || flash[:alert]
    %div{:class => "notice #{'alert' if flash[:alert]}"}
      = flash[:notice] || flash[:alert]
  = render "shared/header"
  %section#wrap.clearfix
    %section#content{class: controller_class}
      = yield
  = render "shared/footer"
  = javascript_include_tag "application"
  = render "shared/analytics"

app/views/layouts/session.html.haml
!!!
/[if IE 7 ] <html lang="en" class="no-js ie7">
/[if IE 8 ] <html lang="en" class="no-js ie8">
/[if IE 9 ] <html lang="en" class="no-js ie9">
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
%head
  %meta{charset: "utf-8"}
  %title 欢迎来到 Funnies!
  = stylesheet_link_tag "funnies"
  = csrf_meta_tag
%body
  - if flash[:notice] || flash[:alert]
    %div{:class => "notice #{'alert' if flash[:alert]}"}
      = flash[:notice] || flash[:alert]
  #session
    #session-inner
      = yield
  = javascript_include_tag "application"
  = render "shared/analytics"

app/views/pages/about.html.haml
:markdown
  ## 豆瓣的来历

  你经常对着书店里的绵绵不绝的封面发呆吗？或者头晕脑涨地从音像店的琳琅满目中逃出？宽带下载和网上购物降临之后，即使在最小的城镇，你的选择也在每天成百上千地增加。这其中一定有你会喜爱的东西，但十有八九它们会在不知不觉中和你擦肩而过。媒体让老少咸宜的大片无处不在，对只适合一群人的东西却显得力不从心。而且，萝卜青菜，各有所爱，不管电视的娱乐编辑和报纸的书评作家多么公正和勤勉，他们的帮助都不可能对所有人同样有效。

  ## 参与豆瓣

  豆瓣没有编辑写手，没有特约文章，没有六百行的首页和跳动的最新专题。豆瓣的藏书甚至没有强加给你的“标准分类”。这里所有的内容，分类，筛选，排序都由和你一样的成员产生和决定。给评论一个“有用”，它的排位会自动上升；贴“我女儿的最爱”给一本书，它会在整个网站的标签分类中出现。豆瓣相信大众的力量，多数人的判断，和数字的智慧。通过网站幕后不断完善之中的算法，有序和有益的结构会从无数特异而可爱的个性中产生。

  豆瓣网站的每个开发管理者也都是豆瓣每日的用户，分享着自己心爱的发现，也从你的参与中受益。我们鼓励你通过点击成员的名号或头像访问别人的个人主页，并充实自己的收藏或评论。这些是豆瓣上最重要和有益的内容。

app/views/pages/copyright.html.haml
:markdown
  ## 第一条

  用户以各种方式使用豆瓣网服务和数据（包括但不限于发表、宣传介绍、转载、浏览及利用豆瓣网或豆瓣网用户发布内容）的过程中，不得以任何方式利用豆瓣网直接或间接从事违反中国法律、以及社会公德的行为，且用户应当恪守下述承诺：

  * 发布、转载或提供的内容符合中国法律、社会公德；
  * 不得干扰、损害和侵犯豆瓣网的各种合法权利与利益；
  * 遵守豆瓣网以及与之相关的网络服务的协议、指导原则、管理细则等；

  ## 第二条

  豆瓣网有权对违反上述承诺的内容予以删除。

  * [Rails Store](http://railsstore.com)  
  * [Github](http://github.com/kelby)  

  对免责声明的解释、修改及更新权均属于豆瓣网所有。

app/views/pages/landing.html.haml
%h1#tagline 在此可阅读所有您喜欢的漫画，就像在报纸上阅读一样！

#signup= link_to "点击注册", new_user_registration_path, class: "signup"

app/views/posts/_form.html.haml
= semantic_form_for post do |f|
  = f.semantic_errors
  = f.inputs do
    = f.input :title
    = f.input :body
  = f.buttons do
    = f.commit_button label: "保存！"

app/views/posts/edit.html.haml
= render partial: "form", locals: { post: post }

app/views/posts/index.html.haml
- posts.each do |post|
  %article
    %header
      %h1= post.title
      = gravatar_for(post.user, size: 20)
      %span= post.user.username
      %time{datetime: post.created_at.strftime("%F")}= post.created_at.strftime("%d, %b %Y")
    =raw RDiscount.new(post.body, :smart).to_html
    - if user_signed_in? && current_user.admin?
      %nav.admin-menu
        = link_to "编辑此文", edit_post_path(post), class: "button admin_button"
        = link_to "删除此文", post_path(post), method: :delete, confirm: "你真的确实要删除此文？", class: "button admin_button"

app/views/posts/new.html.haml
= render :partial => 'form'

app/views/shared/_analytics.html.haml
:javascript
  var _gauges = _gauges || [];
  (function() {
    var t   = document.createElement('script');
    t.type  = 'text/javascript';
    t.async = true;
    t.id    = 'gauges-tracker';
    t.setAttribute('data-site-id', '4da508b6f5a1f5514c000001');
    t.src = '//secure.gaug.es/track.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(t, s);
  })();

app/views/shared/_footer.html.haml
%footer.clearfix
  = link_to "网站源代码", "http://github.com/martinisoft/funnies"
  | #{link_to "版权声明", copyright_path}
  | #{link_to "特此鸣谢", "http://www.railsstore.com/"}

app/views/shared/_header.html.haml
#wrap-banner.clearfix
  #banner-inner.clearfix
    %header
      %h1
        = link_to root_path do
          = image_tag("logo.png", alt: "Funnies")
    %nav#top-menu
      #top-menu-wrap
        %ul#main-menu
          - if user_signed_in?
            %li= link_to "我的漫画", user_comics_path(current_user.username)
            %li= link_to "漫画列表", comics_path
          %li= link_to "关于我们", about_path
          %li= link_to "博客日志", posts_path
          - if user_signed_in? && current_user.admin?
            %li= admin_nav_link

    #account
      - if user_signed_in?
        = gravatar_for(current_user, size: 20)
        = link_to current_user.username, "#", class: "username"
        = link_to "退出", destroy_user_session_path, method: :delete
      - else
        = link_to "登录", new_user_session_path

app/views/subscriptions/new.html.haml
%h2 我要订阅！

app/views/suggestions/new.html.haml
%h2 提交一新漫画

= semantic_form_for suggestion do |f|
  = f.semantic_errors
  = f.inputs do
    = f.input :name
    = f.input :website
    = f.input :reason, label: "为什么提交此漫画？"
  = f.buttons do
    = f.commit_button label: "提交！"